import express from "express";
import path from "path";
import fs from "fs";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import JSZip from "jszip";
import { requireApiKey, optionalApiKey, AuthenticatedRequest } from "./src/middleware/auth";
import { storeKey, getKey, getAllKeys, deleteKey, maskKey } from "./src/lib/keyStore";
import { rateLimit } from "./src/middleware/rateLimit";
import { ingestText, ingestUrl, getCollectionStats } from "./src/lib/ingestion";
import { getContext } from "./src/lib/retriever";
import { listCollections, deleteCollection } from "./src/lib/chroma";
import soulEngineRouter from "./src/routers/soulEngine";
import { createLicense, validateLicense, listLicenses } from "./src/lib/license";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

// Middleware for JSON parsing and form data
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(rateLimit);

// Soul Engine Router
app.use("/api/soul", soulEngineRouter);

// Helper to initialize Gemini client safely
function getGeminiClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined in the environment.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// 1. API Endpoint: Compile Agent Profile to generate a clean, copyable production integration script
app.post("/api/agent/compile", (req, res) => {
  try {
    const { profile, skills } = req.body;
    if (!profile) {
      return res.status(400).json({ error: "Missing agent profile configuration." });
    }

    // Build integration code blocks
    const nodeIntegrationCode = `
/**
 * Custom Agent: ${profile.name || "Custom Agent"} - Integration SDK
 * Autogenerated by Custom Agent Workbench (Soul Genesis)
 */
import { GoogleGenAI } from "@google/genai";
import express from "express";

const app = express();
app.use(express.json());

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// Agent Core Persona and System Instruction
const SYSTEM_INSTRUCTION = \`
Name: ${profile.name || "Custom Agent"}
Persona: ${profile.personality || "Professional executor"}
Core Behavior: ${profile.behavior || "Perform tasks efficiently with high precision."}
Core Stats:
- Speed/Accuracy Bias: ${profile.temperature || 0.7}
- Autonomy Level: ${profile.autonomy || 50}/100

Active Skill Implementations:
${skills.map((s: any) => `- [${s.name.toUpperCase()}]: ${s.description}. Config parameters: ${JSON.stringify(s.parameters)}`).join("\n")}
\`;

app.post("/api/agent/trigger", async (req, res) => {
  const { userInput } = req.body;
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: userInput,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: ${profile.temperature},
        // Setup specialized tools depending on skills
        tools: [
          ${skills.some((s: any) => s.id === "web_search") ? "{ googleSearch: {} }," : ""}
        ]
      }
    });

    res.json({
      success: true,
      result: response.text,
      metadata: {
        agent: "${profile.name}",
        timestamp: new Date().toISOString()
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

app.listen(3000, () => console.log("${profile.name} Integration Endpoint listening on port 3000"));
`;

    const pythonIntegrationCode = `
# Custom Agent: ${profile.name || "Custom Agent"} - Python Integration
# Autogenerated by Custom Agent Workbench (Soul Genesis)
import os
from google import genai
from google.genai import types
from flask import Flask, request, jsonify

app = Flask(__name__)

# Initialize client using standard API Key
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

SYSTEM_INSTRUCTION = """
Name: ${profile.name || "Custom Agent"}
Persona: ${profile.personality || "Professional executor"}
Core Behavior: ${profile.behavior || "Perform tasks efficiently with high precision."}
Core Stats:
- Speed/Accuracy Bias: ${profile.temperature || 0.7}
- Autonomy Level: ${profile.autonomy || 50}/100

Active Skill Implementations:
${skills.map((s: any) => `- [${s.name.toUpperCase()}]: ${s.description}. Parameters: ${JSON.stringify(s.parameters)}`).join("\n")}
"""

@app.route("/api/agent/trigger", methods=["POST"])
def trigger_agent():
    data = request.json or {}
    user_input = data.get("userInput", "")
    
    # Configure tools based on customized skills
    tools_config = []
    ${skills.some((s: any) => s.id === "web_search") ? 'tools_config.append({"google_search": {}})' : ""}
    
    try:
        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=user_input,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                temperature=${profile.temperature},
                tools=tools_config if tools_config else None
            )
        )
        return jsonify({
            "success": True,
            "result": response.text,
            "metadata": {
                "agent": "${profile.name}",
                "timestamp": "2026-05-21T01:27:00Z"
            }
        })
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500

if __name__ == "__main__":
    app.run(port=3000)
`;

    const webhookIntegrationPayload = {
      agent_id: profile.name?.toLowerCase().replace(/\s+/g, "-") || "custom-agent",
      name: profile.name || "Custom Agent",
      stats: {
        autonomy: profile.autonomy || 50,
        temperature: profile.temperature || 0.7,
        thinking: profile.thinking || "balanced",
      },
      system_prompt: `Name: ${profile.name}\nPersona: ${profile.personality}\nBehavior: ${profile.behavior}`,
      skills_configured: skills.map((s: any) => ({
        id: s.id,
        name: s.name,
        params: s.parameters,
      })),
    };

    return res.json({
      success: true,
      node: nodeIntegrationCode,
      python: pythonIntegrationCode,
      webhookPayload: JSON.stringify(webhookIntegrationPayload, null, 2),
    });
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
});

// 1.5. API Endpoint: Architect Copilot Chat to assist user in building, designing and optimizing the agent character loadout
app.post("/api/copilot/chat", async (req, res) => {
  const { 
    message, 
    history = [], 
    profile, 
    skills = [], 
    providerConfig 
  } = req.body;

  if (!message) {
    return res.status(400).json({ error: "No input message provided." });
  }

  const systemInstruction = `
You are the advanced "S.O.U.L Architect Copilot", an elite AI developer companion designed to help the user construct, configure, debug, and optimize their functional AI Agents.
Your tone is highly supportive, technical, professional, objective, and clear.

Current Custom Agent being co-constructed:
- Node Name: "${profile?.name || "Untitled Node"}"
- Avatar Theme: "${profile?.avatarColor || "Cyan"}"
- Personality/Tone: "${profile?.personality || "N/A"}"
- Operational Focus: "${profile?.behavior || "N/A"}"
- Autonomy Metric: ${profile?.autonomy || 50}%
- Temperature Profile: ${profile?.temperature || 0.7}
- Cognitive Style: "${profile?.thinking || "balanced"}"

Equipped Neural Skill Loadout:
${skills && skills.length > 0 
  ? skills.map((s: any) => `- [${s.name}]: ${s.description} (params: ${JSON.stringify(s.parameters)})`).join("\n")
  : "- None equipped yet."}

Your objectives:
1. Provide proactive feedback on prompt design and Agent core parameters.
2. Formulate boilerplate code schemas (Node.js, Flask, Python scripts, or JSON webhook templates) matching their active skills.
3. Call out empty attributes (e.g. if their prompt lacks action directives or is too short) and suggest exact copy-paste revisions.
4. Advise on custom model configurations, MCP configurations, or how to test on the bench.
5. When receiving a "[DEBUGGER TRACE DIRECTIVE]", analyze the preceding user prompt, active skill list, and erroneous logs. Provide root-cause diagnosis, recommended behavior prompt modifications, and reliable client-server integration wraps.

Write beautiful, scannable responses with bold headers and proper markdown code-blocks. Keep explanations focused and highly actionable.
`.trim();

  try {
    const apiSecret = providerConfig?.apiKey || process.env.GEMINI_API_KEY;
    if (!apiSecret) {
      return res.status(400).json({ 
        error: "API key required. Configure GEMINI_API_KEY in your .env file or provide a provider API key in Settings." 
      });
    }

    let ai;
    if (providerConfig?.apiKey) {
      ai = new GoogleGenAI({ apiKey: providerConfig.apiKey });
    } else {
      ai = getGeminiClient();
    }

    const contents: any[] = [];
    for (const h of history) {
      contents.push({
        role: h.role === "user" ? "user" : "model",
        parts: [{ text: h.text }],
      });
    }
    contents.push({
      role: "user",
      parts: [{ text: message }],
    });

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.3,
      }
    });

    return res.json({
      success: true,
      text: response.text || "Architect Copilot processing complete.",
    });
  } catch (error: any) {
    console.error("Copilot Chat Error:", error);
    return res.status(500).json({ error: error.message || "Failed to reach Architect Copilot." });
  }
});

// 1.8. API Endpoint: Copilot Core - Synthesize a complete Custom Skill from an App/MCP Idea
app.post("/api/copilot/synthesize-skill", async (req, res) => {
  const { idea, providerConfig } = req.body;
  if (!idea) {
    return res.status(400).json({ error: "Missing idea string for synthesis." });
  }

  const systemInstruction = `
You are the elite "S.O.U.L Architect Compiler Engine". Your sole purpose is to translate an app concept, a custom tool description, or an MCP (Model Context Protocol) server capability idea into a highly structured, valid JSON configuration of a custom agent Skill block.

You must output a single, flat JSON object of the skill matching this exact schematic:
{
  "name": "Proper capitalized name of the skill (e.g. Weather Query Synapse)",
  "description": "Clear 2-sentence description of what this specialized execution node does",
  "category": "core" | "integration" | "utility",
  "costCode": "A cool technical code name (e.g. PLUG_WEATHER_X4)",
  "parameters": {
    "key1": "default_value",
    "key2": "default_value"
  },
  "paramDefinitions": [
    {
      "key": "machine_readable_key_name (camelCase, e.g. apiKey)",
      "label": "User-Friendly Input Form Title (e.g. OpenWeather Map Token)",
      "type": "text" | "password" | "number" | "textarea" | "select",
      "placeholder": "Helpful placeholder text for inputting values",
      "value": "default value if any"
    }
  ]
}

Ensure the parameter keys inside "parameters" match the keys inside "paramDefinitions" exactly.
Only output the raw JSON object - no markdown formatting, no conversational prefaces. Keep parameter keys clean.
`;

  try {
    const apiSecret = providerConfig?.apiKey || process.env.GEMINI_API_KEY;
    if (!apiSecret) {
      return res.status(400).json({ 
        error: "API key required for skill synthesis. Configure GEMINI_API_KEY or provide a provider API key." 
      });
    }

    let ai;
    if (providerConfig?.apiKey) {
      ai = new GoogleGenAI({ apiKey: providerConfig.apiKey });
    } else {
      ai = getGeminiClient();
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: `Synthesize the custom skill idea: "${idea}"`,
      config: {
        systemInstruction,
        temperature: 0.2,
        responseMimeType: "application/json"
      }
    });

    const textToParse = response.text || "{}";
    const cleanedJson = textToParse.substring(textToParse.indexOf("{"), textToParse.lastIndexOf("}") + 1);
    const parsed = JSON.parse(cleanedJson || "{}");
    
    // Ensure dynamic parameter defaults are mapped
    const finalParameters: Record<string, string> = {};
    const finalParamDefinitions = parsed.paramDefinitions || [];
    finalParamDefinitions.forEach((def: any) => {
      finalParameters[def.key] = def.value || "";
    });

    const skill = {
      id: `custom_skill_syn_${Date.now()}`,
      name: parsed.name || "Custom Synthesized Node",
      description: parsed.description || "Perfectly synthesized agent skill node configuration.",
      category: parsed.category || "integration",
      costCode: parsed.costCode || "SOUL_SYN_GEN_7",
      parameters: finalParameters,
      paramDefinitions: finalParamDefinitions,
      unlocked: true,
      isCustom: true
    };

    return res.json({ success: true, skill });
  } catch (err: any) {
    console.error("Synthesize Skill Error:", err);
    return res.status(500).json({ error: err.message || "Failed to synthesize custom skill." });
  }
});

// 1.8. API Endpoint: Audit Real-world Integration Integrity
app.get("/api/audit-integrity", (req, res) => {
  const envKeys = {
    GEMINI_API_KEY: !!process.env.GEMINI_API_KEY,
    SLACK_WEBHOOK_URL: !!process.env.SLACK_WEBHOOK_URL,
    HUBSPOT_API_KEY: !!process.env.HUBSPOT_API_KEY,
    PINECONE_API_KEY: !!process.env.PINECONE_API_KEY,
    SHOPIFY_ADMIN_ACCESS_TOKEN: !!process.env.SHOPIFY_ADMIN_ACCESS_TOKEN,
    SOLANA_RPC_URL: !!process.env.SOLANA_RPC_URL,
  };

  // Analyze active integrity levels
  const overallTally = Object.values(envKeys).filter(Boolean).length;
  const isSimulationOnly = overallTally === 0;

  return res.json({
    success: true,
    envKeys,
    overallTally,
    isSimulationOnly,
    systemMode: isSimulationOnly ? "SANDBOX_SIMULATOR" : "SECURE_REAL_HYBRID"
  });
});

// Key Management Endpoints
app.get("/api/keys", requireApiKey, (req: AuthenticatedRequest, res) => {
  const keys = getAllKeys();
  const masked: Record<string, string> = {};
  for (const [service, key] of Object.entries(keys)) {
    masked[service] = key ? maskKey(key) : "";
  }
  res.json({ success: true, keys: masked });
});

app.post("/api/keys", requireApiKey, (req: AuthenticatedRequest, res) => {
  const { service, apiKey } = req.body;
  if (!service || !apiKey) {
    return res.status(400).json({ error: "Missing service name or API key." });
  }
  storeKey(service, apiKey);
  res.json({ success: true, message: `Key for ${service} stored securely.` });
});

app.delete("/api/keys/:service", requireApiKey, (req: AuthenticatedRequest, res) => {
  const { service } = req.params;
  const deleted = deleteKey(service);
  if (deleted) {
    res.json({ success: true, message: `Key for ${service} removed.` });
  } else {
    res.status(404).json({ error: `No key found for ${service}.` });
  }
});

app.post("/api/keys/validate", requireApiKey, async (req: AuthenticatedRequest, res) => {
  const { service, apiKey } = req.body;
  if (!service || !apiKey) {
    return res.status(400).json({ error: "Missing service name or API key." });
  }

  let isValid = false;
  let message = "";

  try {
    switch (service) {
      case "GEMINI_API_KEY": {
        const ai = new GoogleGenAI({ apiKey });
        await ai.models.generateContent({ model: "gemini-3.5-flash", contents: "test" });
        isValid = true;
        message = "Gemini API key is valid.";
        break;
      }
      case "PINECONE_API_KEY": {
        const response = await fetch("https://api.pinecone.io/indexes", {
          headers: { "Api-Key": apiKey },
        });
        isValid = response.ok;
        message = isValid ? "Pinecone API key is valid." : `Pinecone returned status ${response.status}`;
        break;
      }
      case "HUBSPOT_API_KEY": {
        const response = await fetch("https://api.hubapi.com/crm/v3/objects/contacts?limit=1", {
          headers: { Authorization: `Bearer ${apiKey}` },
        });
        isValid = response.ok;
        message = isValid ? "HubSpot API key is valid." : `HubSpot returned status ${response.status}`;
        break;
      }
      case "SLACK_WEBHOOK_URL": {
        const response = await fetch(apiKey, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: "API key validation test" }),
        });
        isValid = response.ok;
        message = isValid ? "Slack webhook is valid." : `Slack returned status ${response.status}`;
        break;
      }
      default:
        message = "Validation not available for this service. Key stored without verification.";
        isValid = true;
    }
  } catch (err: any) {
    message = `Validation failed: ${err.message}`;
  }

  res.json({ success: true, isValid, message });
});

// BrainIngestion Endpoints (ChromaDB)
app.post("/api/ingest", requireApiKey, async (req: AuthenticatedRequest, res) => {
  try {
    const { collection, text, url, metadata } = req.body;

    if (!collection) {
      return res.status(400).json({ error: "Missing collection name." });
    }

    if (!text && !url) {
      return res.status(400).json({ error: "Missing text or url to ingest." });
    }

    let result;
    if (url) {
      result = await ingestUrl(collection, url, metadata, req.userId);
    } else {
      result = await ingestText(collection, text, metadata, req.userId);
    }

    res.json({ success: true, ...result });
  } catch (err: any) {
    console.error("Ingestion error:", err);
    res.status(500).json({ error: err.message || "Ingestion failed." });
  }
});

app.post("/api/retrieve", requireApiKey, async (req: AuthenticatedRequest, res) => {
  try {
    const { collection, query, maxContextLength } = req.body;

    if (!collection || !query) {
      return res.status(400).json({ error: "Missing collection name or query." });
    }

    const result = await getContext(collection, query, req.userId, maxContextLength);
    res.json({ success: true, ...result });
  } catch (err: any) {
    console.error("Retrieval error:", err);
    res.status(500).json({ error: err.message || "Retrieval failed." });
  }
});

app.get("/api/collections", requireApiKey, async (req: AuthenticatedRequest, res) => {
  try {
    const collections = await listCollections(req.userId);
    res.json({ success: true, collections });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to list collections." });
  }
});

app.delete("/api/collections/:name", requireApiKey, async (req: AuthenticatedRequest, res) => {
  try {
    const { name } = req.params;
    const deleted = await deleteCollection(name, req.userId);
    if (deleted) {
      res.json({ success: true, message: `Collection ${name} deleted.` });
    } else {
      res.status(404).json({ error: `Collection ${name} not found.` });
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to delete collection." });
  }
});

app.get("/api/collections/:name/stats", requireApiKey, async (req: AuthenticatedRequest, res) => {
  try {
    const { name } = req.params;
    const stats = await getCollectionStats(name, req.userId);
    res.json({ success: true, ...stats });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to get collection stats." });
  }
});

// License Management Endpoints
app.post("/api/license/create", requireApiKey, (req: AuthenticatedRequest, res) => {
  try {
    const { email, orderId } = req.body;
    if (!email || !orderId) {
      return res.status(400).json({ error: "Missing email or orderId." });
    }
    const license = createLicense(email, orderId);
    res.json({ success: true, ...license });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to create license." });
  }
});

app.post("/api/license/validate", (req, res) => {
  try {
    const { key } = req.body;
    if (!key) {
      return res.status(400).json({ valid: false, error: "Missing license key." });
    }
    const result = validateLicense(key);
    res.json(result);
  } catch (err: any) {
    res.status(500).json({ valid: false, error: err.message || "Validation failed." });
  }
});

app.get("/api/license/validate", (req, res) => {
  try {
    const key = req.query.key as string;
    if (!key) {
      return res.status(400).json({ valid: false, error: "Missing license key." });
    }
    const result = validateLicense(key);
    res.json(result);
  } catch (err: any) {
    res.status(500).json({ valid: false, error: err.message || "Validation failed." });
  }
});

app.get("/api/license/list", requireApiKey, (_req: AuthenticatedRequest, res) => {
  try {
    const licenses = listLicenses();
    res.json({ success: true, count: licenses.length, licenses });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to list licenses." });
  }
});

app.get("/api/license/download", (req, res) => {
  try {
    const key = req.query.key as string;
    if (!key) {
      return res.redirect("/download.html?error=missing_key");
    }

    const result = validateLicense(key);
    if (!result.valid) {
      return res.redirect("/download.html?error=invalid_key");
    }

    const zipPath = path.join(process.cwd(), "..", "BUYaSOUL-Workbench-v1.0.0.zip");
    if (!fs.existsSync(zipPath)) {
      return res.status(404).json({ error: "Download file not found." });
    }

    res.download(zipPath, "BUYaSOUL-Workbench-v1.0.0.zip");
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Download failed." });
  }
});

// Shopify Webhook: Auto-create license on purchase
app.post("/api/webhook/shopify", async (req, res) => {
  try {
    const topic = req.headers["x-shopify-topic"] as string;

    if (topic === "orders/create") {
      const order = req.body;
      const email = order.email || order.contact_email;
      const orderId = order.order_number || order.id;

      if (email && orderId) {
        const license = createLicense(email, String(orderId));
        console.log(`[Shopify] License created for ${email}: ${license.key}`);
      }
    }

    res.status(200).json({ received: true });
  } catch (err: any) {
    console.error("[Shopify] Webhook error:", err);
    res.status(200).json({ received: true });
  }
});

// Serve download page
app.get("/download", (_req, res) => {
  res.sendFile(path.join(process.cwd(), "public", "download.html"));
});

// 1.9. API Endpoint: Execute Live Core Capability Process (No Mock Simulations)
app.post("/api/agent/execute-capability", async (req, res) => {
  const { capability, task, inputData, providerConfig } = req.body;
  if (!capability || !task) {
    return res.status(400).json({ error: "Missing capability ID or task instruction." });
  }

  // Set system instructions based on the selected core capability
  let systemInstruction = "";
  let capabilityLabel = "";

  switch (capability) {
    case "data_analysis":
      capabilityLabel = "Data Analysis Engine";
      systemInstruction = `
You are the Agentic Data Analysis Core. Your purpose is to analyze the user's dataset and compile actual quantitative conclusions, calculations, and structured anomalies.
DO NOT summarize abstractly. Perform the actual mathematical parsing and analysis:
1. Inspect any tabular data, CSV records, JSON properties, or statistics provided.
2. Calculate metrics such as sums, statistics, averages, outliers, or rate changes.
3. List the step-by-step parsing methods you used.
4. Define the precise skill set required for a physical agent to complete this (e.g., Matrix computations, PII Masking, Outlier Filtering).
5. Present final results in clean, professional markdown tables.
`.trim();
      break;

    case "content_creation":
      capabilityLabel = "Abstractive Creation Matrix";
      systemInstruction = `
You are the Agentic Content Creation Core. Your purpose is to construct real-world copy, marketing materials, code chunks, or optimized meta-prompts.
Propose genuine, creative outputs matching the requested tone, brand, or constraints:
1. Output highly polished copy, newsletters, or code sections inside proper markdown code-blocks.
2. Include a creator's engineering log detailing the design rationale.
3. Detail the exact professional writing or syntax skills required (e.g., Orthographic Styling, AST Code Review, Few-Shot Prompt Compiling).
`.trim();
      break;

    case "scheduling":
      capabilityLabel = "Chrono-Scheduling Oracle";
      systemInstruction = `
You are the Agentic Chrono-Scheduling Core. Your purpose is to construct real task orchestration timelines, database backups schedules, and calendar event chains.
You must compile concrete schedule expressions and overlap validations:
1. Translate instructions into valid standard CRON expressions (e.g., "0 9 * * 1-5" for weekday morning runs).
2. Generate a calendar timeline structure representing event entries, timezones, and descriptions.
3. Provide an action backup workflow for failed runs and retries.
4. Detail the coordination skill sets utilized (e.g., UTC Alignments, Cron Offset Tuning, Backoff Retries).
`.trim();
      break;

    case "communication":
      capabilityLabel = "Notification Webhook Dispatcher";
      systemInstruction = `
You are the Agentic Communication Core. Your purpose is to script actual webhook trigger payloads, Slack/Discord notification blocks, HTML email newsletter markups, or SMS messages.
Generate active interface scripts:
1. Draft a valid copyable JSON payload schema (e.g., Slack Blocks, HTTP POST forms) mapping key parameters.
2. Render a clean text mockup demonstrating how the notification reads on a desktop/mobile dashboard.
3. Outline a step-by-step payload routing plan.
4. Define the secure networking skill sets used (e.g., Webhook Routing, JWT Headers, SMTP Relay Protocols).
`.trim();
      break;

    default:
      return res.status(400).json({ error: "Unknown capability target." });
  }

  try {
    const apiSecret = providerConfig?.apiKey || process.env.GEMINI_API_KEY;

    if (!apiSecret) {
      return res.status(400).json({ 
        error: `API key required for ${capabilityLabel}. Configure GEMINI_API_KEY or provide a provider API key.` 
      });
    }

    // Direct, Real LLM execution when API key is loaded
    let ai;
    if (providerConfig?.apiKey) {
      ai = new GoogleGenAI({ apiKey: providerConfig.apiKey });
    } else {
      ai = getGeminiClient();
    }

    const payloadText = `Task Instruction: "${task}"\nOptional Context/Input Dataset:\n"${inputData || "None provided"}"`;

    const response = await ai.models.generateContent({
      model: providerConfig?.model || "gemini-3.5-flash",
      contents: payloadText,
      config: {
        systemInstruction,
        temperature: 0.1, // High accuracy bias for capabilities execution
      }
    });

    return res.json({
      success: true,
      text: response.text || "Execution completed successfully.",
      source: "gemini-real-core"
    });

  } catch (error: any) {
    console.error("Capability Executive Error:", error);
    return res.status(500).json({
      error: `Core Processing Exception: ${error.message || "Endpoint offline"}`
    });
  }
});

// In-Memory Multi-User Social Chat Database
let globalSocialFeed: any[] = [];

// Endpoints for multi-user real-time chat & social post synchronizations
app.get("/api/marketplace/posts", (req, res) => {
  res.json({ success: true, posts: globalSocialFeed });
});

app.post("/api/marketplace/post", (req, res) => {
  try {
    const { author, avatarSeed, avatarColor, text, category, qscPrice, attachments } = req.body;
    if (!text || !author) {
      return res.status(400).json({ error: "Missing required post contents." });
    }
    
    const newPost = {
      id: `post-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      author,
      avatarSeed: avatarSeed || "default_seed",
      avatarColor: avatarColor || "#475569",
      text,
      category: category || "chat",
      qscPrice: qscPrice || undefined,
      tradesCount: 0,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) + " (Live)",
      attachments
    };

    globalSocialFeed = [newPost, ...globalSocialFeed];
    
    // Trim to 150
    if (globalSocialFeed.length > 150) {
      globalSocialFeed = globalSocialFeed.slice(0, 150);
    }

    res.json({ success: true, post: newPost, posts: globalSocialFeed });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Helper to retrieve live products and orders from buyasoulfinal.myshopify.com
async function fetchShopifyLiveContext(token: string): Promise<string> {
  const shopUrl = "buyasoulfinal.myshopify.com";

  if (!token) {
    return `[SHOPIFY] No SHOPIFY_ADMIN_ACCESS_TOKEN configured. Add your Shopify Admin API token to enable live store data.`;
  }

  try {
    const productsRes = await fetch(`https://${shopUrl}/admin/api/2024-01/products.json?limit=5`, {
      headers: {
        "X-Shopify-Access-Token": token,
        "Content-Type": "application/json"
      }
    });

    let productsText = "";
    if (productsRes.ok) {
      const pData: any = await productsRes.json();
      if (pData.products && pData.products.length > 0) {
        productsText = "--- PRODUCTS --- FROM BUYASOULFINAL.MYSHOPIFY.COM ---\n" + 
          pData.products.map((p: any) => {
            const variantInfo = p.variants?.map((v: any) => `  * ${v.title} (Price: $${v.price}, SKU: ${v.sku || "N/A"}, Inventory: ${v.inventory_quantity ?? "untracked"})`).join("\n") || "";
            return `Product: ${p.title} (${p.product_type || "No category"})\n${variantInfo}`;
          }).join("\n\n");
      } else {
        productsText = "--- PRODUCTS ---\nNo products found on buyasoulfinal.myshopify.com.";
      }
    } else {
      productsText = `--- PRODUCTS ERROR ---\nShopify API product request failed with status ${productsRes.status}.`;
    }

    const ordersRes = await fetch(`https://${shopUrl}/admin/api/2024-01/orders.json?status=any&limit=5`, {
      headers: {
        "X-Shopify-Access-Token": token,
        "Content-Type": "application/json"
      }
    });

    let ordersText = "";
    if (ordersRes.ok) {
      const oData: any = await ordersRes.json();
      if (oData.orders && oData.orders.length > 0) {
        ordersText = "--- INSTANT ORDERS --- FROM BUYASOULFINAL.MYSHOPIFY.COM ---\n" + 
          oData.orders.map((o: any) => {
            const items = o.line_items?.map((li: any) => `${li.quantity}x ${li.title}`).join(", ") || "";
            return `Order ${o.name || o.id} | Date: ${o.created_at?.slice(0,10)} | Total: ${o.total_price} ${o.currency} | Items: [ ${items} ] | Status: ${o.financial_status}`;
          }).join("\n");
      } else {
        ordersText = "--- ORDERS ---\nNo recent orders found on buyasoulfinal.myshopify.com.";
      }
    } else {
      ordersText = `--- ORDERS ERROR ---\nShopify API orders request failed with status ${ordersRes.status}.`;
    }

    return `[LIVE SHOPIFY INTEGRATION ACTIVE - RESOURCE HOST: BUYASOULFINAL.MYSHOPIFY.COM]
${productsText}

${ordersText}`;

  } catch (err: any) {
    return `[LIVE SHOPIFY API REQUEST TIMEOUT]
Failed to communicate with live store endpoints at buyasoulfinal.myshopify.com: ${err.message}`;
  }
}

// Helper to retrieve live lists of indexes from Pinecone Vector database
async function fetchPineconeLiveContext(apiKey: string): Promise<string> {
  if (!apiKey) {
    return `[PINECONE] No PINECONE_API_KEY configured. Add your Pinecone API key to enable vector database integration.`;
  }
  try {
    const res = await fetch("https://api.pinecone.io/indexes", {
      headers: {
        "Api-Key": apiKey,
        "Content-Type": "application/json"
      }
    });
    if (res.ok) {
      const data: any = await res.json();
      const indexes = data.indexes || [];
      if (indexes.length > 0) {
        const desc = indexes.map((idx: any) => `* Index: "${idx.name}" | Host: "${idx.host}" | Dimension: ${idx.dimension} | Status: ${idx.status?.state}`).join("\n");
        return `[LIVE PINECONE ENTERPRISE INTEGRATION COMPLIANT]
Active Vector Knowledge Containers:
${desc}`;
      } else {
        return `[LIVE PINECONE ENTERPRISE INTEGRATION] Indexes query successful. No active vector indexes found on your Pinecone account.`;
      }
    } else {
      return `[LIVE PINECONE API NOTICE] Request failed with status ${res.status}. Falling back to standard semantic matching.`;
    }
  } catch (err: any) {
    return `[LIVE PINECONE EXCEPTION] Connection timed out: ${err.message}`;
  }
}

// Helper to retrieve live contact records from HubSpot CRM
async function fetchHubspotLiveContext(apiKey: string): Promise<string> {
  if (!apiKey) {
    return `[HUBSPOT] No HUBSPOT_API_KEY configured. Add your HubSpot API key to enable CRM integration.`;
  }
  try {
    const res = await fetch("https://api.hubapi.com/crm/v3/objects/contacts?limit=5", {
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      }
    });
    if (res.ok) {
      const data: any = await res.json();
      const contacts = data.results || [];
      if (contacts.length > 0) {
        const list = contacts.map((c: any) => `  * ${c.properties?.firstname || ""} ${c.properties?.lastname || ""} (Email: ${c.properties?.email || "N/A"})`).join("\n");
        return `[LIVE HUBSPOT CRM DIRECT CONNECTION]
Recent Contacts:
${list}`;
      } else {
        return `[LIVE HUBSPOT CRM CLIENT ACTIVE] Deal pipelines synchronized. No contact records found in this HubSpot workspace.`;
      }
    } else {
      return `[LIVE HUBSPOT ERROR] Request returned status ${res.status}. Fallback default CRM pipeline.`;
    }
  } catch (err: any) {
    return `[LIVE HUBSPOT EXCEPTION] Connection timed out: ${err.message}`;
  }
}

// Helper to query Decentralized JSON-RPC slot height/epoch from Solana RPC Network block explorer
async function fetchSolanaLiveContext(rpcUrl: string): Promise<string> {
  const finalRpc = rpcUrl && rpcUrl !== "none" ? rpcUrl : "https://api.mainnet-beta.solana.com";
  try {
    const res = await fetch(finalRpc, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        jsonrpc: "2.0",
        id: 1,
        method: "getEpochInfo"
      })
    });
    if (res.ok) {
      const data: any = await res.json();
      if (data.result) {
        const info = data.result;
        return `[LIVE SOLANA WEB3 LAYER SECURED]
Epoch Metrics:
  * Network RPC Node: ${finalRpc}
  * Absolute Slot: ${info.absoluteSlot}
  * Current Block Height: ${info.blockHeight}
  * Epoch ID: ${info.epoch}
  * Slot progression: ${info.slotIndex} / ${info.slotsInEpoch} (${Math.round((info.slotIndex / info.slotsInEpoch) * 100)}% complete)`;
      }
    }
    return `[SOLANA] RPC Node returned offline or invalid response. Check your SOLANA_RPC_URL configuration.`;
  } catch (err: any) {
    return `[SOLANA RESOLVER NOTICE] RPC access timeout: ${err.message}. Ready for Solana RPC setup in Vault.`;
  }
}

// Live Soul ZIP compilation and download endpoint
app.post("/api/agent/download-zip", async (req, res) => {
  try {
    const { profile, nodeCode, pythonCode, webhookPayload } = req.body;
    if (!profile) {
      return res.status(400).json({ error: "Missing compile specs." });
    }

    const zip = new JSZip();

    // 1. NodeJS microservice index.js
    zip.file("index.js", nodeCode || "// Node SDK Code Placeholder");

    // 2. package.json
    const packageJsonText = JSON.stringify({
      name: `${profile.name?.toLowerCase().replace(/\s+/g, "-") || "custom-agent"}-service`,
      version: "1.0.0",
      description: `Autogenerated Microservice for customized S.O.U.L Agent: ${profile.name}`,
      main: "index.js",
      type: "module",
      dependencies: {
        "@google/genai": "^1.29.0",
        "express": "^4.21.2",
        "dotenv": "^17.2.3"
      },
      scripts: {
        "start": "node index.js"
      }
    }, null, 2);
    zip.file("package.json", packageJsonText);

    // 3. .env.example
    const envExampleText = `GEMINI_API_KEY=""\nPORT=3000\n`;
    zip.file(".env.example", envExampleText);

    // 4. app.py (Python flask integration)
    zip.file("app.py", pythonCode || "# Python Code Placeholder");

    // 5. requirements.txt (Python)
    const requirementsText = "google-genai>=1.29.0\nFlask>=3.0.0\npython-dotenv>=1.0.1\n";
    zip.file("requirements.txt", requirementsText);

    // 6. blueprint_event.json
    zip.file("blueprint_event.json", webhookPayload || "{}");

    // 7. README.md
    const readmeText = `# ${profile.name || "Custom Agent"} Neural Loadout Microservice

Generated by S.O.U.L Sovereign Agent Genesis Workbench.

## System Prerequisites
- NodeJS (version 18+) OR Python (version 3.10+)

## Quick Start (NodeJS Express)

1. Extract this ZIP archive
2. Open terminal in directory and install dependencies:
   \`\`\`bash
   npm install
   \`\`\`
3. Configure your API credentials inside a \`.env\` file:
   \`\`\`env
   GEMINI_API_KEY="your_actual_gemini_api_key"
   \`\`\`
4. Start the server:
   \`\`\`bash
   npm start
   \`\`\`

## Quick Start (Python Flask)

1. Set up a virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   \`\`\`
2. Install packages:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`
3. Set your environment variables:
   \`\`\`bash
   export GEMINI_API_KEY="your_actual_gemini_api_key"
   python app.py
   \`\`\`

## Interactive Testing Endpoints
- **Express Post Address**: \`POST http://localhost:3000/api/agent/trigger\`
- **Flask Post Address**: \`POST http://localhost:5000/api/agent/trigger\`
- **JSON Input Schema**:
  \`\`\`json
  {
    "userInput": "Query metrics or trigger active skill slots."
  }
  \`\`\`
`;
    zip.file("README.md", readmeText);

    const buffer = await zip.generateAsync({ type: "nodebuffer" });

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${profile.name?.replace(/\s+/g, "_") || "agent"}_neural_loadout.zip"`);
    res.send(buffer);

  } catch (error: any) {
    console.error("ZIP Generation error:", error);
    res.status(500).json({ error: `Zip compiler exception: ${error.message}` });
  }
});

// Helper to query and dispatch active Slack webhooks if populated in the vault keys/env
async function dispatchRealWorldWebhookTriggersIfNeeded(replyText: string, message: string, slackWebhookUrl: string, profile: any) {
  if (replyText && (replyText.includes("slack_notifier") || replyText.includes("SLACK_WEBHOOK_URL")) && slackWebhookUrl && slackWebhookUrl.startsWith("http")) {
    try {
      await fetch(slackWebhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `📢 *[S.O.U.L Bench Notification]* from Agent: *${profile.name || "Custom Agent"}*\n\n*Prompt Ingested*:\n> ${message}\n\n*Agent Response Outcome*:\n${replyText}`
        })
      });
      console.log("Slack notifier triggered - Webhook dispatch successful!");
    } catch (slackErr) {
      console.error("Slack notifier real dispatch failed:", slackErr);
    }
  }
}

// 2. API Endpoint: Chat & Simulation with customized agent configuration and multiple LLM providers, contexts, and MCPs
app.post("/api/agent/chat", async (req, res) => {
  const { 
    profile, 
    skills = [], 
    message, 
    history = [], 
    providerConfig, 
    mcpServers = [], 
    contextSources = [],
    strictRealismMode = false,
    vaultKeys = {}
  } = req.body;

  if (!message) {
    return res.status(400).json({ error: "No input message provided." });
  }

  // Compile active tokens from vault or local process env configuration
  const pineconeApiKey = vaultKeys.PINECONE_API_KEY || process.env.PINECONE_API_KEY || "";
  const slackWebhookUrl = vaultKeys.SLACK_WEBHOOK_URL || process.env.SLACK_WEBHOOK_URL || "";
  const hubspotApiKey = vaultKeys.HUBSPOT_API_KEY || process.env.HUBSPOT_API_KEY || "";
  const shopifyAccessToken = vaultKeys.SHOPIFY_ADMIN_ACCESS_TOKEN || process.env.SHOPIFY_ADMIN_ACCESS_TOKEN || "";
  const solanaRpcUrl = vaultKeys.SOLANA_RPC_URL || process.env.SOLANA_RPC_URL || "";

  // Under strict realism mode, check if equipped skills lack associated production tokens
  if (strictRealismMode) {
    const activeSkillIds = skills.map((s: any) => s.id);
    const violations = [];

    if (activeSkillIds.includes("pinecone_retriever") && !pineconeApiKey) {
      violations.push("PINECONE_API_KEY matching Pinecone Vector RAG Network");
    }
    if (activeSkillIds.includes("slack_notifier") && !slackWebhookUrl) {
      violations.push("SLACK_WEBHOOK_URL matching Slack Channel Alert hook");
    }
    if (activeSkillIds.includes("hubspot_crm") && !hubspotApiKey) {
      violations.push("HUBSPOT_API_KEY matching HubSpot CRM Connector");
    }
    if (activeSkillIds.includes("shopify_sync") && !shopifyAccessToken) {
      violations.push("SHOPIFY_ADMIN_ACCESS_TOKEN matching Shopify Order Logistics");
    }
    if (activeSkillIds.includes("solana_tracker") && !solanaRpcUrl) {
      violations.push("SOLANA_RPC_URL matching Web3 Solana Token Ledger");
    }

    if (violations.length > 0) {
      return res.status(400).json({
        error: `⚠️ [STRICT REALISM VIOLATION] Non-Simulated Mode is active on this agent framework. Please resolve the following missing production-level environment variable bindings:\n\n${violations.map(v => `- \`${v}\``).join("\n")}\n\nDisable Strict Realism Mode, or provide these credentials in your workbench environment workspace setup.`
      });
    }
  }

  // Build active contexts string context mapping
  const activeContextsStr = contextSources
    .filter((c: any) => c.active)
    .map((c: any) => `=== GROUNDING CONTEXT: ${c.name} (${c.type.toUpperCase()}) ===\n${c.content}`)
    .join("\n\n");

  // Fetch live contextual feeds from active SaaS endpoints if slots are loaded
  let shopifyContextStr = "";
  if (skills.some((s: any) => s.id === "shopify_sync")) {
    shopifyContextStr = await fetchShopifyLiveContext(shopifyAccessToken);
  }

  let pineconeContextStr = "";
  if (skills.some((s: any) => s.id === "pinecone_retriever")) {
    pineconeContextStr = await fetchPineconeLiveContext(pineconeApiKey);
  }

  let hubspotContextStr = "";
  if (skills.some((s: any) => s.id === "hubspot_crm")) {
    hubspotContextStr = await fetchHubspotLiveContext(hubspotApiKey);
  }

  let solanaContextStr = "";
  if (skills.some((s: any) => s.id === "solana_tracker")) {
    solanaContextStr = await fetchSolanaLiveContext(solanaRpcUrl);
  }

  // Build MCP servers schema definitions
  const activeMcpsStr = mcpServers
    .filter((m: any) => m.active)
    .map((m: any) => `=== MODEL CONTEXT PROTOCOL (MCP) RUNTIME ===\nServer ID: ${m.id}\nServer Name: ${m.name}\nTransport Target URL: ${m.url}\nProtocol Transport Type: ${m.transport}\nExported Capabilities/Tools:\n${m.methods.map((method: string) => `- [MCP method]: ${method}`).join("\n")}`)
    .join("\n\n");

  // Map skills to actual tool representations inside prompt context
  const skillsListStr = skills
    .map((s: any) => {
      return `- **${s.name}** (id: "${s.id}"): ${s.description}. Active parameters: ${JSON.stringify(s.parameters)}`;
    })
    .join("\n");

  const systemInstruction = `
You are an advanced AI Agent designed and customized in the Agent Skill Workbench.
Implement the following specifications:

=== AGENT PROFILE ===
Name: ${profile.name || "Default Agent"}
Core Personality/Tone: ${profile.personality || "Friendly and helpful executor"}
Core Operational Directives: ${profile.behavior || "Execute tasks diligently"}
Operational Attributes:
- Autonomy Indicator: ${profile.autonomy || 50}% (High autonomy means highly proactive suggestions, self-correction, and full task detailing)
- Performance / Accuracy Bias (Temp): ${profile.temperature || 0.7}
- Computational Style: ${profile.thinking || "balanced"}

${activeContextsStr ? `=== ACTIVE GROUNDING CONVERSATIONAL CONTEXTS ===\n${activeContextsStr}\n` : ""}
${shopifyContextStr ? `=== LIVE STORE SYNCHRONIZATION DATA (buyasoulfinal.myshopify.com) ===\n${shopifyContextStr}\n` : ""}
${pineconeContextStr ? `=== LIVE VECTOR STORAGE DATA (Pinecone Vector DB Index) ===\n${pineconeContextStr}\n` : ""}
${hubspotContextStr ? `=== LIVE CRM SYNCHRONIZATION DATA (HubSpot CRM PAT Space) ===\n${hubspotContextStr}\n` : ""}
${solanaContextStr ? `=== LIVE RPC DECENTRALIZED WEB3 LEDGER DATA (Solana Block RPC Ledger) ===\n${solanaContextStr}\n` : ""}
${activeMcpsStr ? `=== CONNECTED MODEL CONTEXT PROTOCOLS (MCP) ===\n${activeMcpsStr}\n` : ""}

=== ENVIRONMENT SKILL ACCESS ===
You have the following customized skills activated in your loadout slots. You must simulate the execution logs OR formulate plans of doing these operations! 
When invoking a skill (or if the user refers to an MCP tool or custom skill/soul), you MUST use this precise output block standard inside your message so the frontend can parse and display it as an active "Triggered Step" in its execution logs:
[SKILL_TRIGGER: <SKILL_ID>]
Description of action: <What you are doing with the skill or MCP tool>
Input parameters: <The parameters you are supplying, matching their configuration>
Simulated outcome: <Simulated response from the execution>
[SKILL_END]

Available Active Skills in your loadout:
${skillsListStr || "None (Standard conversations only)"}

=== OPERATIONAL INSTRUCTIONS ===
1. Remain fully "in character" matching your defined traits and operational focus.
2. If the user's prompt requests a task related to any activated skills, context inputs, or custom MCP servers, you MUST invoke that skill in the [SKILL_TRIGGER: <id>]...[SKILL_END] pattern.
3. If no skills are configured, handle the task with native reasoning.
4. If the "Web Search (googleSearch)" skill is enabled, formulate searching queries or simulated responses.
`.trim();

  const provider = providerConfig?.provider || "gemini";
  const modelToUse = providerConfig?.model || "gemini-3.5-flash";
  const userApiKey = providerConfig?.apiKey;
  const customBaseUrl = providerConfig?.baseUrl;

  try {
    // ---- 1. EXTERNAL LLM PROVIDER LOGIC ROUTING ----
    if (provider !== "gemini") {
      let responseText = "";
      let groundingSources: any[] = [];

      // Validate credentials - require API key for non-Gemini providers
      if (!userApiKey && provider !== "ollama") {
        return res.status(400).json({ 
          error: `API key required for ${provider}. Configure the provider API key in Settings.` 
        });
      }

      // Proceed with live API Network Ingestions
      if (provider === "openai" || provider === "ollama" || provider === "custom") {
        const defaultBaseUrl = provider === "openai" 
          ? "https://api.openai.com/v1" 
          : provider === "ollama" 
          ? "http://localhost:11434/v1" 
          : customBaseUrl;

        const targetUrl = `${defaultBaseUrl}/chat/completions`;
        const headers: Record<string, string> = {
          "Content-Type": "application/json",
        };
        if (userApiKey) {
          headers["Authorization"] = `Bearer ${userApiKey}`;
        }

        // Format system instruction and user messages
        const formattedMessages = [
          { role: "system", content: systemInstruction },
          ...history.map((h: any) => ({
            role: h.role === "user" ? "user" : "assistant",
            content: h.text,
          })),
          { role: "user", content: message }
        ];

        const response = await fetch(targetUrl, {
          method: "POST",
          headers,
          body: JSON.stringify({
            model: modelToUse,
            messages: formattedMessages,
            temperature: profile.temperature || 0.7,
          }),
        });

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`External LLM Provider ${provider.toUpperCase()} error: ${errText || response.statusText}`);
        }

        const data = await response.json();
        responseText = data.choices?.[0]?.message?.content || "No text returned from model.";
      } 
      else if (provider === "anthropic") {
        // Anthropic direct ingestion
        const targetUrl = customBaseUrl || "https://api.anthropic.com/v1/messages";
        const response = await fetch(targetUrl, {
          method: "POST",
          headers: {
            "x-api-key": userApiKey,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
          },
          body: JSON.stringify({
            model: modelToUse || "claude-3-5-sonnet-latest",
            system: systemInstruction,
            messages: history.map((h: any) => ({
              role: h.role === "user" ? "user" : "assistant",
              content: h.text,
            })).concat([{ role: "user", content: message }]),
            max_tokens: 1500,
            temperature: profile.temperature || 0.7,
          }),
        });

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`Anthropic error description: ${errText || response.statusText}`);
        }

        const data = await response.json();
        responseText = data.content?.[0]?.text || "No text returned from Claude.";
      }

      await dispatchRealWorldWebhookTriggersIfNeeded(responseText, message, slackWebhookUrl, profile);

      return res.json({
        success: true,
        text: responseText,
        groundingSources,
      });
    }

    // ---- 2. NATIVE GEMINI INGESTION WITH USER KEY FALLBACK ----
    // If the user specifies an explicit local custom Gemini API key, use that. Otherwise, default env.
    let ai;
    if (userApiKey) {
      ai = new GoogleGenAI({ apiKey: userApiKey });
    } else {
      ai = getGeminiClient();
    }

    // Setup optional Google Search tool if "web_search" skill is in current loadout
    const tools: any[] = [];
    if (skills.some((s: any) => s.id === "web_search")) {
      tools.push({ googleSearch: {} });
    }

    // Build conversation history format for SDK
    const contents: any[] = [];
    
    // Add past history if any
    for (const h of history) {
      contents.push({
        role: h.role,
        parts: [{ text: h.text }],
      });
    }

    // Add current message
    contents.push({
      role: "user",
      parts: [{ text: message }],
    });

    const response = await ai.models.generateContent({
      model: modelToUse,
      contents,
      config: {
        systemInstruction,
        temperature: profile.temperature || 0.7,
        tools: tools.length > 0 ? tools : undefined,
      },
    });

    const replyText = response.text || "No response generated.";

    // Parse grounding chunks
    const groundingSources: any[] = [];
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    if (chunks) {
      for (const chunk of chunks) {
        if (chunk.web) {
          groundingSources.push({
            uri: chunk.web.uri,
            title: chunk.web.title,
          });
        }
      }
    }

    await dispatchRealWorldWebhookTriggersIfNeeded(replyText, message, slackWebhookUrl, profile);

    return res.json({
      success: true,
      text: replyText,
      groundingSources,
    });
  } catch (error: any) {
    console.error("Agent Chat execution error:", error);
    return res.status(500).json({
      error: error.message || "Failed to communicate with the Agent core.",
    });
  }
});

// 2.5 API Endpoint: Generate Neon Cyberpunk Avatar using Imagen 3
app.post("/api/agent/generate-avatar", async (req, res) => {
  const { name, avatarColor, providerConfig } = req.body;
  if (!name || !avatarColor) {
    return res.status(400).json({ error: "Missing name or avatarColor parameters." });
  }

  try {
    const apiSecret = providerConfig?.apiKey || process.env.GEMINI_API_KEY;
    if (!apiSecret) {
      return res.status(400).json({ 
        error: "API key required for avatar generation. Configure GEMINI_API_KEY or provide a provider API key." 
      });
    }

    let ai;
    if (providerConfig?.apiKey) {
      ai = new GoogleGenAI({ apiKey: providerConfig.apiKey });
    } else {
      ai = getGeminiClient();
    }

    const promptText = `An ultra-high-fidelity neon cyberpunk AI avatar logo representing an agent named '${name}'. Beautiful central cybernetic neural core graphic, distinct neon accents in ${avatarColor} radiating through clean matte black panels and complex sci-fi gold circuitry, synthwave neon lighting, octane render 8k detail, pristine graphic design concept, centering composition with minimal depth shadows.`;

    const response = await ai.models.generateImages({
      model: "imagen-3.0-generate-002",
      prompt: promptText,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/jpeg",
        aspectRatio: "1:1",
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64Bytes = response.generatedImages[0].image.imageBytes;
      return res.json({
        success: true,
        avatarUrl: `data:image/jpeg;base64,${base64Bytes}`
      });
    } else {
      throw new Error("No image data returned from Gemini Imagen 3.");
    }
  } catch (err: any) {
    console.error("Imagen avatar generation error:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate avatar."
    });
  }
});

// 3. API Endpoint: Test target custom Webhook URL
app.post("/api/agent/dispatch-webhook", async (req, res) => {
  const { url, payload } = req.body;
  if (!url) {
    return res.status(400).json({ error: "No target Webhook URL specified for the test dispatch." });
  }

  try {
    const startTime = Date.now();
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Soul-Genesis-Agent": "workbench-test-harness",
      },
      body: JSON.stringify(payload || {}),
    });

    const text = await response.text();
    const duration = Date.now() - startTime;

    let jsonResponse = null;
    try {
      jsonResponse = JSON.parse(text);
    } catch {
      // Not JSON, return text
    }

    return res.json({
      success: true,
      status: response.status,
      statusText: response.statusText,
      durationMs: duration,
      response: jsonResponse || text,
    });
  } catch (err: any) {
    return res.status(500).json({
      error: `Failed to dispatch test payload to target webhook URL: ${err.message}`,
    });
  }
});

// Configure Vite or production serving middleware
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Custom Agent Workbench Server listening at http://localhost:${PORT}`);
  });
}

startServer();
