module.exports.MANIFEST = {
    name: 'npm_publish',
    description: 'Skill: npm_publish',
    version: '1.0.0',
    inputs: {},
    output: { schema: 'ok/error' }
};

module.exports.run = async (params) => {
    // Standardized implementation
};
'use strict';

const fs = require('fs');
const path = require('path');

const PLT_AFFINITY = { profit: 0.9, love: 0.2, tax: 0.3 };

function _slugify(value) {
    return String(value || 'allie-package')
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') || 'allie-package';
}

function skill_npm_publish(input, brain, memory) {
    const name = input.name || input.packageName || '';
    const version = input.version || '1.0.0';
    const description = input.description || '';
    const entry = input.entry || 'index.js';
    const dependencies = input.dependencies || {};

    if (!name) {
        return Promise.resolve({
            skill: 'npm_publish',
            plt_affinity: PLT_AFFINITY,
            status: 'error',
            error: 'No package name provided',
            timestamp: Date.now(),
        });
    }

    const packageJson = {
        name,
        version,
        description: description || 'A BUYaSOUL-powered package',
        main: entry,
        scripts: {
            test: 'echo "Error: no test specified" && exit 1',
            prepublish: 'npm test',
        },
        keywords: ['buyasoul', 'plt-press', 'soul'],
        license: 'MIT',
        dependencies: Object.keys(dependencies).length > 0 ? dependencies : {},
    };

    const readme = `# ${name}\n\n${description || 'Generated by GSK — The Greatest Agent Ever'}\n\n## Install\n\n\`\`\`bash\nnpm install ${name}\n\`\`\`\n\n## Usage\n\n\`\`\`js\nconst ${name.replace(/[^a-z]/g, '')} = require('${name}');\n\`\`\`\n\n---\n*Powered by [BUYaSOUL Core](https://buyasoul.online) · PLT Press*`;

    const outputDir = input.outputDir || path.join(process.cwd(), 'generated', 'npm', _slugify(name));
    const packageJsonPath = input.packageJsonPath || path.join(outputDir, 'package.json');
    const readmePath = path.join(outputDir, 'README.md');
    const entryPath = path.join(outputDir, entry);

    try {
        if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
        if (!fs.existsSync(path.dirname(entryPath))) fs.mkdirSync(path.dirname(entryPath), { recursive: true });
        fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n', 'utf8');
        if (!fs.existsSync(entryPath)) {
            fs.writeFileSync(entryPath, `module.exports = function ${name.replace(/[^a-z]/g, '')}() {\n  return '${name} ready';\n};\n`, 'utf8');
        }
        fs.writeFileSync(readmePath, readme, 'utf8');
    } catch (e) {
        return Promise.resolve({
            skill: 'npm_publish',
            plt_affinity: PLT_AFFINITY,
            status: 'error',
            error: e.message,
            timestamp: Date.now(),
        });
    }

    if (memory && typeof memory.witness === 'function') {
        memory.witness({
            type: 'skill_artifact',
            content: `npm package scaffold written: ${outputDir}`,
            weight: 0.5,
            tags: ['skill', 'npm_publish', 'artifact'],
        }).catch(() => {});
    }

    return Promise.resolve({
        skill: 'npm_publish',
        plt_affinity: PLT_AFFINITY,
        status: 'package_written',
        name,
        version,
        description,
        package_json: packageJson,
        readme,
        entry_point: entry,
        files: [packageJsonPath, readmePath, entryPath],
        next_step: 'Run npm pack or npm publish from the generated directory',
        timestamp: Date.now(),
    });
}

module.exports = { skill_npm_publish, PLT_AFFINITY };

