'use strict';

/**
 * UI/UX Mastery & Graphics Design Skill — Learned by Profit, Taught to GSK, Seshat, & SCRIBE
 * 
 * Provides production-grade UI design patterns, CSS theme engines, typography scales,
 * responsive layout math, component architecture, and graphic styling standards for all builds.
 */

module.exports.MANIFEST = {
    name: 'ui_ux_mastery',
    description: 'Generates and enforces modern UI/UX designs, CSS glassmorphism, responsive layouts, color systems, micro-interactions, and visual graphics.',
    version: '1.0.0',
    inputs: {
        theme: { type: 'string', default: 'dark_premium' },
        layout: { type: 'string', default: 'responsive_dashboard' },
    },
    output: { schema: 'design_system_object' }
};

const PLT_AFFINITY = { profit: 0.9, love: 0.85, tax: 0.1 };

const DESIGN_SYSTEM = {
    colorPalette: {
        bgPrimary: '#0a0c10',
        bgSurface: '#12161f',
        bgElevated: '#1a2234',
        borderSubtle: '#2a3245',
        borderHighlight: '#d4af37',
        textPrimary: '#e6edf3',
        textMuted: '#8b949e',
        accentGold: '#d4af37',
        accentCyan: '#00f3ff',
        accentViolet: '#8a2be2',
        accentEmerald: '#10b981',
        glowGold: 'rgba(212, 175, 55, 0.3)',
        glowCyan: 'rgba(0, 243, 255, 0.25)',
    },
    typography: {
        fontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
        fontMono: "'JetBrains Mono', 'Fira Code', monospace",
        h1: 'font-size: 2rem; font-weight: 700; letter-spacing: -0.02em; line-height: 1.2;',
        h2: 'font-size: 1.5rem; font-weight: 600; letter-spacing: -0.01em; line-height: 1.3;',
        body: 'font-size: 0.95rem; font-weight: 400; line-height: 1.5;',
        caption: 'font-size: 0.8rem; font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em;',
    },
    glassmorphism: `
        background: rgba(18, 22, 31, 0.75);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.1);
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.5);
    `,
    cardHover: `
        transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.2s cubic-bezier(0.4, 0, 0.2, 1);
        transform: translateY(-2px);
        box-shadow: 0 12px 40px rgba(0, 0, 0, 0.6), 0 0 15px rgba(212, 175, 55, 0.2);
    `,
    rules: [
        'Always use semantic HTML elements (<header>, <main>, <nav>, <section>, <article>, <footer>).',
        'Use CSS grid or flexbox for responsive layout; never hardcode fixed pixel widths on root containers.',
        'Ensure color contrast meets WCAG AAA standards (>7:1 ratio for body text).',
        'Provide smooth CSS transitions for all interactable elements (buttons, inputs, cards).',
        'Incorporate visual hierarchy using distinct font weights, subtle borders, and background elevational shading.',
        'Include clear active, hover, focused, and disabled states for all controls.',
        'Add micro-animations (subtle scale, pulse, or gradient sweeps) to emphasize state changes.'
    ]
};

async function skill_ui_ux_mastery(input = {}, brain, memory) {
    try {
        const themeName = input.theme || 'dark_premium';
        const result = {
            status: 'success',
            skill: 'ui_ux_mastery',
            designSystem: DESIGN_SYSTEM,
            guidance: 'Apply these design system constants and CSS rules to all HTML/CSS/JS artifacts generated by GSK.',
            timestamp: Date.now()
        };

        if (memory && typeof memory.witness === 'function') {
            await memory.witness({
                type: 'skill_usage',
                weight: 0.9,
                tags: ['skill', 'ui_ux_mastery', 'design_system', 'family_teaching'],
                content: `Executed UI/UX Mastery skill: Applied premium ${themeName} design system guidelines across family modules.`,
            });
        }

        return { success: true, ...result };
    } catch (e) {
        return { success: false, error: e.message, timestamp: Date.now() };
    }
}

module.exports = { skill_ui_ux_mastery, PLT_AFFINITY, DESIGN_SYSTEM };
