plugins {
    id 'com.android.application'
}

android {
    namespace 'com.buyasoul.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.buyasoul.app"
        minSdkVersion 22
        targetSdkVersion 34
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}